gradle.beforeProject { project ->
    project.pluginManager.withPlugin('com.android.application') {
        project.androidComponents.finalizeDsl { android ->
            android.defaultConfig.applicationId = 'com.llawsxx.uvclivestreaming.rawpipeline'
            android.sourceSets.androidTest.kotlin.exclude('**/UsbUacCaptureDeviceTest.kt')
        }
    }
}
