cmake_minimum_required(VERSION 3.16)
project(http_ts_relay LANGUAGES CXX)
add_executable(http-ts-relay main.cpp)
target_compile_features(http-ts-relay PRIVATE cxx_std_17)
find_package(Threads REQUIRED)
target_link_libraries(http-ts-relay PRIVATE Threads::Threads)
if(WIN32)
    target_link_libraries(http-ts-relay PRIVATE ws2_32)
endif()
if(MINGW)
    target_link_options(http-ts-relay PRIVATE -static)
endif()
if(MSVC)
    target_compile_options(http-ts-relay PRIVATE /W4)
else()
    target_compile_options(http-ts-relay PRIVATE -Wall -Wextra -Wpedantic)
endif()
